//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajeroAutomaticoApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int IdOperacion { get; set; }
        public string NroTarjeta { get; set; }
        public string TipoOperacion { get; set; }
        public Nullable<long> CantidadARetirar { get; set; }
        public Nullable<System.DateTime> FechaOperacion { get; set; }
    }
}
