//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajeroAutomaticoApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public string PinTarjeta { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string NroTarjeta { get; set; }
        public Nullable<long> SaldoActual { get; set; }
        public bool IsBlocked { get; set; }
    }
}
